# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hramirezq
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: force
# "service" is the name of this project. This will also be added to your AWS resource names.
service: force-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DEBUG: ${env:DEBUG, 0}
    STAGE: ${env:STAGE, "prod"}
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:343218203795:table/Peoples

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - DATABASE_URL
  dynamodb:
    stages:
      - dev
    start:
      port: 9000
      inMemory: true
      migrate: true
      seed: true
      noStart: false
  esbuild:
    bundle: true
    minify: false
    watch:
      pattern: [ 'src/**/*.ts' ] # match only typescript files in src directory
      ignore: [ 'temp/**/*' ]
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-dynamodb
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-auto-swagger

package:
  exclude:
    - tests/**
resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Peoples
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  createPeople:
    handler: src/handlers/CreatePeopleHandler.createPeople
    timeout: 30
    events:
      - http:
          path: people
          method: post
  getPeople:
    handler: src/handlers/GetPeopleHandler.getPeople
    timeout: 30
    events:
      - http:
          path: people/{id}
          method: get
  getAllPeople:
    handler: src/handlers/GetAllPeopleHandler.getAllPeople
    timeout: 30
    events:
      - http:
          path: people/
          method: get