// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "force-api",
    "version": "1"
  },
  "paths": {
    "/people": {
      "post": {
        "summary": "createPeople",
        "description": "",
        "operationId": "createPeople.post.people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/people/{id}": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get.people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/people/": {
      "get": {
        "summary": "getAllPeople",
        "description": "",
        "operationId": "getAllPeople.get.people/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};